USE db24;
/*DELIMITER $$
CREATE TRIGGER MyTBL21a_guard1 BEFORE INSERT ON MyTBL_21a
FOR EACH ROW
BEGIN
DECLARE a varchar(100);
SELECT CURRENT_USER() INTO @a;
SIGNAL SQLSTATE '50000' SET message_text=@a;
END; $$
DELIMITER ;

INSERT INTO MyTBL_21a (Title) VALUE ('AAA');*/

CREATE TABLE `MyTBL_21b` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(20) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
